### PR TITLE
feat: make quality level list iterable.

### PR DESCRIPTION
**Pull request by gjanblaszczyk**
## Description
The PR makes a quality level list iterable.

## Specific Changes proposed
Add iterator to the QualityLevelList.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Unit Tests updated or fixed
  - [x] Docs/guides updated
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Sounds good to me, though, this would be a breaking changing since it won't work on IE11.

**Comment by gjanblaszczyk** [comment]
I have just added a Symbol checking to avoid problems on IE 11. So right now, the PR doesn't introduce any breaking changes...

**Review by misteroneill — CHANGES_REQUESTED** [review]
Let's not worry about IE11 and just roll all these open PRs into a major version update of the plugin. Then we can roll that into Video.js 8.

**Comment by gjanblaszczyk** [comment]
Ok, I have just reverted the Symbol checking.

**Review by misteroneill — APPROVED** [review]

**Pull request merged**
